// src/renderer/src/components/modules/OscillatorModule.jsx
import "../../assets/styles/OscillatorModule.css";

import { useEffect, useState } from "react";
import Slider from "../Slider";
import { InPort, OutPort } from "../Port";

const __FREQ = 0;
const __FREQ_MOD_AMT = 1;
const __PUL_WIDTH = 2;
const __PUL_WIDTH_MOD_AMT = 3;

// TODO: will components being run twice lead to problems for C++?
function OscillatorModule(props) {
  const { moduleId, xCoord, yCoord } = props;

  const params = {};
  const handlers = {};

  [params[__FREQ], handlers[__FREQ]] = useState(8.175799 * Math.pow(2, 3));
  [params[__FREQ_MOD_AMT], handlers[__FREQ_MOD_AMT]] = useState(0.0);
  [params[__PUL_WIDTH], handlers[__PUL_WIDTH]] = useState(0.5);
  [params[__PUL_WIDTH_MOD_AMT], handlers[__PUL_WIDTH_MOD_AMT]] = useState(0.0);

  useEffect(() => {
    console.log(`api.addModule(moduleId: ${moduleId}, moduleType: __OSCILLATOR);`);
    api.addModule(moduleId, 2);
    return () => {
      console.log(`api.removeModule(moduleId: ${moduleId});`);
      api.removeModule(moduleId);
    };
  }, []);

  useEffect(() => {
    api.updateParam(moduleId, __FREQ, params[__FREQ]);
  }, [params[__FREQ]]);

  useEffect(() => {
    api.updateParam(moduleId, __FREQ_MOD_AMT, params[__FREQ_MOD_AMT]);
  }, [params[__FREQ_MOD_AMT]]);

  useEffect(() => {
    api.updateParam(moduleId, __PUL_WIDTH, params[__PUL_WIDTH]);
  }, [params[__PUL_WIDTH]]);

  useEffect(() => {
    api.updateParam(moduleId, __PUL_WIDTH_MOD_AMT, params[__PUL_WIDTH_MOD_AMT]);
  }, [params[__PUL_WIDTH_MOD_AMT]]);

  return (
    <div className="module module-outer oscillator" style={{ top: yCoord, left: xCoord }}>
      <div className="module-inner">
        <div className="module-type">VCO</div>
        <Slider
          label="FREQ"
          min={0}
          max={1000}
          value={params[__FREQ]}
          onChange={(event) => {
            handlers[__FREQ](parseFloat(event.target.value));
          }}
        />
        <div>{params[__FREQ]}</div>
        <div>{moduleId}</div>

        <div className="ports">
          {/* TODO: __IN_PORT_... naming */}
          <InPort moduleId={moduleId} inPortId={0} label="FM" />
          <InPort moduleId={moduleId} inPortId={1} label="PWM" />
          <InPort moduleId={moduleId} inPortId={2} label="V/OCT" />
          <InPort moduleId={moduleId} inPortId={3} label="SYNC" />
        </div>

        <div className="ports">
          {/* TODO: __OUT_PORT_... naming */}
          <OutPort moduleId={moduleId} outPortId={0} label="SIN" />
          <OutPort moduleId={moduleId} outPortId={1} label="TRI" />
          <OutPort moduleId={moduleId} outPortId={2} label="SAW" />
          <OutPort moduleId={moduleId} outPortId={3} label="SQR" />
        </div>
      </div>
    </div>
  );
}

export default OscillatorModule;

// src/renderer/src/components/modules/OscillatorModule.svelte
<script lang="ts" module>
  export function addOscillatorModule(moduleId: string): Module {
    return {
      moduleId,
      moduleType: ModuleType.__OSCILLATOR,
      inPorts: {
        [OscillatorInPortType.__FREQ_MOD]: { cableId: null },
        [OscillatorInPortType.__PUL_WIDTH_MOD]: { cableId: null },
        [OscillatorInPortType.__VOLT_PER_OCT]: { cableId: null },
        [OscillatorInPortType.__SYNC]: { cableId: null },
      },
      outPorts: {
        [OscillatorOutPortType.__SIN]: { cableIds: [] },
        [OscillatorOutPortType.__TRI]: { cableIds: [] },
        [OscillatorOutPortType.__SAW]: { cableIds: [] },
        [OscillatorOutPortType.__SQR]: { cableIds: [] },
        [OscillatorOutPortType.__PUL]: { cableIds: [] },
      },
      xCoord: 0,
      yCoord: 0,
      isDropped: true,
      width: 50 * 4,
      height: 50 * 8,
    };
  }
</script>

<script lang="ts">
  import Module from "./Module.svelte";
  import InPort from "../InPort.svelte";
  import OutPort from "../OutPort.svelte";
  import Knob from "../Knob.svelte";

  let { module, cables } = $props();

  const params = $state({
    [OscillatorParamType.__FREQ]: 8.175799 * Math.pow(2, 3),
    [OscillatorParamType.__FREQ_MOD_AMT]: 0.0,
    [OscillatorParamType.__PUL_WIDTH]: 0.5,
    [OscillatorParamType.__PUL_WIDTH_MOD_AMT]: 0.0,
  });
</script>

<Module {module}>
  <Knob label="FREQ" min={0} max={1000} bind:value={params[OscillatorParamType.__FREQ]} />
  <div>{params[OscillatorParamType.__FREQ]}</div>

  <div class="ports">
    <InPort {module} inPortId={OscillatorInPortType.__FREQ_MOD} label="FM" {cables} />
    <InPort {module} inPortId={OscillatorInPortType.__PUL_WIDTH_MOD} label="PWM" {cables} />
    <InPort {module} inPortId={OscillatorInPortType.__VOLT_PER_OCT} label="V/OCT" {cables} />
    <InPort {module} inPortId={OscillatorInPortType.__SYNC} label="SYNC" {cables} />
  </div>
  <div class="ports">
    <OutPort {module} outPortId={OscillatorOutPortType.__SIN} label="SIN" {cables} />
    <OutPort {module} outPortId={OscillatorOutPortType.__TRI} label="TRI" {cables} />
    <OutPort {module} outPortId={OscillatorOutPortType.__SAW} label="SAW" {cables} />
    <OutPort {module} outPortId={OscillatorOutPortType.__SQR} label="SQR" {cables} />
  </div>
</Module>

<style>
  .ports {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
  }
</style>
